name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: POST to Vercel Deploy Hook
        run: curl -s -X POST "${{ secrets.VERCEL_HOOK_URL }}"
